// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAzbjIkszt-vb1waKT70dIJZp6GoS45jI',
    appId: '1:1084402498830:web:ce5a1da4d800a30b3e2b5f',
    messagingSenderId: '1084402498830',
    projectId: 'myflutterproj-10549',
    authDomain: 'myflutterproj-10549.firebaseapp.com',
    storageBucket: 'myflutterproj-10549.appspot.com',
    measurementId: 'G-MFVE645X4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPYaL5hNDGE-ngeiuAQnx5x5lc9upj8o',
    appId: '1:1084402498830:android:aabae8563b6f1c203e2b5f',
    messagingSenderId: '1084402498830',
    projectId: 'myflutterproj-10549',
    storageBucket: 'myflutterproj-10549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFVxqgG3LCOm45bDgJJ2TghIx1KUy9_4',
    appId: '1:1084402498830:ios:d07f22b49e9d13603e2b5f',
    messagingSenderId: '1084402498830',
    projectId: 'myflutterproj-10549',
    storageBucket: 'myflutterproj-10549.appspot.com',
    iosClientId: '1084402498830-q8den4h0buugvtqq9qchc3um558sdash.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
